# Generated by Django 4.0.4 on 2022-05-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_filter',
            new_name='label',
        ),
    ]
