# Generated by Django 4.0.4 on 2022-05-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street',
            new_name='address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
